apiVersion: apps/v1
kind: Deployment
metadata:
  name: claimreview
  labels:
    app: claimreview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claimreview
  template:
    metadata:
      labels:
        app: claimreview
    spec:
      containers:
        - name: claimreview
          image: "username/claimreview:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
