name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./claimrequest/pom.xml
          mvn clean package -f ./claimreview/pom.xml
          mvn clean package -f ./customercenter/pom.xml
          mvn clean package -f ./블랙유저/pom.xml

      - name: Docker Build and push for Claimrequest
        uses: docker/build-push-action@v4
        with:
          context: ./claimrequest
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/claimrequest:latest
            ghcr.io/${{ github.repository }}/claimrequest:${{ github.ref_name }}
            
      - name: Docker Build and push for Claimreview
        uses: docker/build-push-action@v4
        with:
          context: ./claimreview
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/claimreview:latest
            ghcr.io/${{ github.repository }}/claimreview:${{ github.ref_name }}
            
      - name: Docker Build and push for Customercenter
        uses: docker/build-push-action@v4
        with:
          context: ./customercenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customercenter:latest
            ghcr.io/${{ github.repository }}/customercenter:${{ github.ref_name }}
            
      - name: Docker Build and push for 블랙유저
        uses: docker/build-push-action@v4
        with:
          context: ./블랙유저
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/블랙유저:latest
            ghcr.io/${{ github.repository }}/블랙유저:${{ github.ref_name }}
            
