---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: claimrequest
  labels:
    app: claimrequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claimrequest
  template:
    metadata:
      labels:
        app: claimrequest
    spec:
      containers:
        - name: claimrequest
          image: username/claimrequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: claimreview
  labels:
    app: claimreview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claimreview
  template:
    metadata:
      labels:
        app: claimreview
    spec:
      containers:
        - name: claimreview
          image: username/claimreview:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customercenter
  labels:
    app: customercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customercenter
  template:
    metadata:
      labels:
        app: customercenter
    spec:
      containers:
        - name: customercenter
          image: username/customercenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 블랙유저
  labels:
    app: 블랙유저
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 블랙유저
  template:
    metadata:
      labels:
        app: 블랙유저
    spec:
      containers:
        - name: 블랙유저
          image: username/블랙유저:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: claimrequest
  labels:
    app: claimrequest
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: claimrequest


---


apiVersion: v1
kind: Service
metadata:
  name: claimreview
  labels:
    app: claimreview
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: claimreview


---


apiVersion: v1
kind: Service
metadata:
  name: customercenter
  labels:
    app: customercenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customercenter


---


apiVersion: v1
kind: Service
metadata:
  name: 블랙유저
  labels:
    app: 블랙유저
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 블랙유저

